title: Bowen Liu's Homepage
page-top-title: Bowen Liu
top-section-bg-text: Computer Science
home-subtitle: Bowen Liu&ensp;|&ensp;刘博文
copyright-text: '&copy; Bowen Liu 2025-2026. All Rights Reserved.'
